### ISSUE TITLE
Remove dependency on io-like

### ISSUE THREAD

**Issue by Quintus** [Quintus/ruby-xz#10]
ruby-xz currently depends on the [io-like gem](https://github.com/javanthropus/io-like), which appears to not be developed anymore. It also [relies on an internal API of io-like](https://github.com/Quintus/ruby-xz/blob/v0.2.1/lib/xz/stream_reader.rb#L192-L196), so getting rid of this dependency would be fairly nice.

Vale,
Quintus

**Comment by imoverclocked** [comment]
:+1: io-like is pretty ancient now and broke some resolver code while running under ruby 2.x.

**Comment by ninkendo** [comment]
Filed https://github.com/Quintus/ruby-xz/issues/13 as a separate issue for the resolver code breakage, because it's probably worthy of calling out separately for any poor soul searching google.

**Comment by Quintus** [comment]
> broke some resolver code while running under ruby 2.x.

This was not io-like’s fault, but mine. See https://github.com/Quintus/ruby-xz/issues/13#issuecomment-156066194 for what caused it most likely.

Valete,
Quintus

**Comment by imoverclocked** [comment]
Nice find!
