### ISSUE TITLE
how to generate a lzma-js compatible string to decode in browser?

### ISSUE THREAD

**Issue by maykefreitas** [Quintus/ruby-xz#16]
Hi I want to generate a compatible string in backend to decode at browser with https://github.com/LZMA-JS/LZMA-JS, can you help me?

Example: http://lzma-js.github.io/LZMA-JS/demos/advanced_demo.html

**Comment by Quintus** [comment]
ruby-xz implements the LZMA compression (by wrapping liblzma). That algorithm is standardised. Any other implementation that implements LZMA can decompress data compressed with ruby-xz/liblzma. Extensive documentation on how to use ruby-xz is available [online](http://quintus.github.io/ruby-xz/).

I've never used the library you linked to, so I can't comment on how to use that one.
